### ISSUE TITLE
Lib Implementation for rustfft

### ISSUE THREAD

**Issue by dynamite-bud** [wasmerio/rustfft#2]
Write a library implementation for `rustfft`:

Package should have following implementations:

 - [ ] [`Complex`](https://docs.rs/num-complex/0.4.0/num_complex/struct.Complex.html)
 - [ ] Multiple [algorithms](https://docs.rs/rustfft/latest/rustfft/algorithm/index.html)
 - [ ] [FftPlanner](https://docs.rs/rustfft/latest/rustfft/struct.FftPlanner.html)
 - [ ] Direction for FftPlanner and algorithms

**Comment by Michael-F-Bryan** [comment]
This was closed in #6.
